### ISSUE TITLE
add paseo testnet 

### ISSUE THREAD

**Issue by muddlebee** [kheopswap/kheopswap#36]
![{C429B8CB-8C11-444B-879D-010F5E489DC9}](https://github.com/user-attachments/assets/1c6407b2-4d9b-4eca-8352-e90aecf1858a)

will be nice to have paseo testnet as option too :) as more cross chain functions are maintained here

**Comment by 0xKheops** [comment]
Hi @muddlebee , yes i will add it very soon

I was waiting for AssetConvertion pallet to be added but it looks like it's there now
